/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriel.interfaceGrafica;

import br.com.gabriel.Objeto.Animal;
import br.com.gabriel.Objeto.Grupo;
import br.com.gabriel.Objeto.Lobo;
import br.com.gabriel.Objeto.Zoologico;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class CadastroDeAnimais extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeAnimais
     */
    
    Zoologico z = new Zoologico(1);
    
    public void desabilitarLobo(){
        this.jTFDataNascimentoLobo.setEnabled(false);
        this.jTFTamanhoLobo.setEnabled(false);
        this.jTFPesoLobo.setEnabled(false);
    }
    public void habilitarLobo(){
        this.jTFDataNascimentoLobo.setEnabled(true);
        this.jTFTamanhoLobo.setEnabled(true);
        this.jTFPesoLobo.setEnabled(true);
    }
    public void desabilitarPeixe(){
        this.jTFTipoPeixe.setEnabled(false);
    }
    public void habilitarPeixe(){
        this.jTFTipoPeixe.setEnabled(true);
    }
    public CadastroDeAnimais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBSalvar = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jRBPeixe = new javax.swing.JRadioButton();
        jRBLobo = new javax.swing.JRadioButton();
        jPGrupo = new javax.swing.JPanel();
        jLTituloGrupo = new javax.swing.JLabel();
        jLNomeGrupo = new javax.swing.JLabel();
        jLDescricaoGrupo = new javax.swing.JLabel();
        jTFNomeGrupo = new javax.swing.JTextField();
        jTFDescricaoGrupo = new javax.swing.JTextField();
        jPAnimal = new javax.swing.JPanel();
        jLDescricaoAnimal = new javax.swing.JLabel();
        jLStatusAnimal = new javax.swing.JLabel();
        jTFDescricaoAnimal = new javax.swing.JTextField();
        jTFStatusAnimal = new javax.swing.JTextField();
        jPLobo = new javax.swing.JPanel();
        jLTituloLobo = new javax.swing.JLabel();
        jLPesoLobo = new javax.swing.JLabel();
        jLTamanhoLobo = new javax.swing.JLabel();
        jTFPesoLobo = new javax.swing.JTextField();
        jTFTamanhoLobo = new javax.swing.JTextField();
        jLDataNascimentoLobo = new javax.swing.JLabel();
        jTFDataNascimentoLobo = new javax.swing.JTextField();
        jPPeixe = new javax.swing.JPanel();
        jLTituloPeixe = new javax.swing.JLabel();
        jLTipoPeixe = new javax.swing.JLabel();
        jTFTipoPeixe = new javax.swing.JTextField();
        jLTituloAnimal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBMostrarCadastrados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBSalvar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jLTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTitulo.setText("Cadastro de Animal");

        jRBPeixe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRBPeixe.setText("Peixe");
        jRBPeixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPeixeActionPerformed(evt);
            }
        });

        jRBLobo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jRBLobo.setText("Lobo");
        jRBLobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLoboActionPerformed(evt);
            }
        });

        jPGrupo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLTituloGrupo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLTituloGrupo.setText("Grupo");

        jLNomeGrupo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLNomeGrupo.setText("Nome");

        jLDescricaoGrupo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLDescricaoGrupo.setText("Descrição");

        jTFNomeGrupo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTFDescricaoGrupo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPGrupoLayout = new javax.swing.GroupLayout(jPGrupo);
        jPGrupo.setLayout(jPGrupoLayout);
        jPGrupoLayout.setHorizontalGroup(
            jPGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGrupoLayout.createSequentialGroup()
                .addComponent(jLTituloGrupo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDescricaoGrupo)
                    .addComponent(jLNomeGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNomeGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTFDescricaoGrupo))
                .addContainerGap())
        );
        jPGrupoLayout.setVerticalGroup(
            jPGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGrupoLayout.createSequentialGroup()
                .addComponent(jLTituloGrupo)
                .addGap(18, 18, 18)
                .addGroup(jPGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeGrupo)
                    .addComponent(jTFNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDescricaoGrupo)
                    .addComponent(jTFDescricaoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        jPAnimal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLDescricaoAnimal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLDescricaoAnimal.setText("Descrição");

        jLStatusAnimal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLStatusAnimal.setText("Status");

        jTFDescricaoAnimal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTFStatusAnimal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jPLobo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLTituloLobo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLTituloLobo.setText("Lobo");

        jLPesoLobo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLPesoLobo.setText("Peso");

        jLTamanhoLobo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLTamanhoLobo.setText("Tamanho");

        jTFPesoLobo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTFTamanhoLobo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLDataNascimentoLobo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLDataNascimentoLobo.setText("Data Nascimento");

        jTFDataNascimentoLobo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPLoboLayout = new javax.swing.GroupLayout(jPLobo);
        jPLobo.setLayout(jPLoboLayout);
        jPLoboLayout.setHorizontalGroup(
            jPLoboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoboLayout.createSequentialGroup()
                .addGroup(jPLoboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLTituloLobo)
                    .addComponent(jLPesoLobo)
                    .addComponent(jLTamanhoLobo)
                    .addComponent(jLDataNascimentoLobo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFDataNascimentoLobo)
                    .addComponent(jTFTamanhoLobo)
                    .addComponent(jTFPesoLobo))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPLoboLayout.setVerticalGroup(
            jPLoboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoboLayout.createSequentialGroup()
                .addComponent(jLTituloLobo)
                .addGap(18, 18, 18)
                .addComponent(jLPesoLobo)
                .addGap(8, 8, 8)
                .addComponent(jTFPesoLobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLTamanhoLobo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFTamanhoLobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLDataNascimentoLobo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFDataNascimentoLobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPPeixe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLTituloPeixe.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLTituloPeixe.setText("Peixe");

        jLTipoPeixe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLTipoPeixe.setText("Tipo");

        jTFTipoPeixe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPPeixeLayout = new javax.swing.GroupLayout(jPPeixe);
        jPPeixe.setLayout(jPPeixeLayout);
        jPPeixeLayout.setHorizontalGroup(
            jPPeixeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPeixeLayout.createSequentialGroup()
                .addGroup(jPPeixeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTituloPeixe)
                    .addComponent(jLTipoPeixe))
                .addGap(0, 46, Short.MAX_VALUE))
            .addComponent(jTFTipoPeixe)
        );
        jPPeixeLayout.setVerticalGroup(
            jPPeixeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPeixeLayout.createSequentialGroup()
                .addComponent(jLTituloPeixe)
                .addGap(18, 18, 18)
                .addComponent(jLTipoPeixe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTipoPeixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLTituloAnimal.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLTituloAnimal.setText("Animal");

        javax.swing.GroupLayout jPAnimalLayout = new javax.swing.GroupLayout(jPAnimal);
        jPAnimal.setLayout(jPAnimalLayout);
        jPAnimalLayout.setHorizontalGroup(
            jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAnimalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDescricaoAnimal)
                    .addComponent(jLStatusAnimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFDescricaoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jTFStatusAnimal))
                .addGap(28, 28, 28))
            .addGroup(jPAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPLobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPPeixe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPAnimalLayout.createSequentialGroup()
                .addComponent(jLTituloAnimal)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPAnimalLayout.setVerticalGroup(
            jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAnimalLayout.createSequentialGroup()
                .addComponent(jLTituloAnimal)
                .addGap(4, 4, 4)
                .addGroup(jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDescricaoAnimal)
                    .addComponent(jTFDescricaoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStatusAnimal)
                    .addComponent(jTFStatusAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPLobo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPPeixe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jBMostrarCadastrados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBMostrarCadastrados.setText("Mostrar Cadastrados");
        jBMostrarCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarCadastradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSalvar)
                    .addComponent(jBMostrarCadastrados)
                    .addComponent(jRBPeixe)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jRBLobo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTitulo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTitulo)
                        .addGap(28, 28, 28)
                        .addComponent(jPGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBPeixe)
                            .addComponent(jRBLobo))
                        .addGap(37, 37, 37)
                        .addComponent(jBSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBMostrarCadastrados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBLoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLoboActionPerformed
        // TODO add your handling code here:
        desabilitarPeixe();
        this.jRBPeixe.setSelected(false);
        habilitarLobo();
    }//GEN-LAST:event_jRBLoboActionPerformed

    private void jRBPeixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPeixeActionPerformed
        // TODO add your handling code here:
        desabilitarLobo();
        this.jRBLobo.setSelected(false);
        habilitarPeixe();
    }//GEN-LAST:event_jRBPeixeActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:
        if(this.jRBLobo.isSelected()){
            SimpleDateFormat stf = new SimpleDateFormat("dd/MM/yyyy");
            float peso = 0, tamanho = 0;
            Date dataNascimento = null;
            Grupo grupo;
            String descricao;
            char status = 0;
            
            descricao = this.jTFDescricaoAnimal.getText();
            try{
            status = this.jTFStatusAnimal.getText().charAt(0);
            }catch(StringIndexOutOfBoundsException siobe){
                JOptionPane.showMessageDialog(this, siobe);
            }
            try{
            dataNascimento = stf.parse(jTFDataNascimentoLobo.getText());
            }catch(ParseException pe){
                JOptionPane.showMessageDialog(this, pe);
            }
            try{
            peso = Float.parseFloat(this.jTFPesoLobo.getText());
            tamanho = Float.parseFloat(this.jTFTamanhoLobo.getText());
            }catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(this, nfe);
            }            
            grupo = new Grupo(0, this.jTFNomeGrupo.getText(), this.jTFDescricaoGrupo.getText());
            z.getAnimais().add(new Lobo(peso, tamanho, dataNascimento, grupo, 0, descricao, status));
            
        }else if(jRBPeixe.isSelected()){
            
        }else {
            JOptionPane.showMessageDialog(this, "Favor selecionar um tipo de animal! ");
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBMostrarCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarCadastradosActionPerformed
        // TODO add your handling code here:
        String animais = "";
        for (Animal animal : z.getAnimais()) {
            animais += animal.toString();            
        }
        JOptionPane.showMessageDialog(this, animais);
    }//GEN-LAST:event_jBMostrarCadastradosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeAnimais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMostrarCadastrados;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JLabel jLDataNascimentoLobo;
    private javax.swing.JLabel jLDescricaoAnimal;
    private javax.swing.JLabel jLDescricaoGrupo;
    private javax.swing.JLabel jLNomeGrupo;
    private javax.swing.JLabel jLPesoLobo;
    private javax.swing.JLabel jLStatusAnimal;
    private javax.swing.JLabel jLTamanhoLobo;
    private javax.swing.JLabel jLTipoPeixe;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLTituloAnimal;
    private javax.swing.JLabel jLTituloGrupo;
    private javax.swing.JLabel jLTituloLobo;
    private javax.swing.JLabel jLTituloPeixe;
    private javax.swing.JPanel jPAnimal;
    private javax.swing.JPanel jPGrupo;
    private javax.swing.JPanel jPLobo;
    private javax.swing.JPanel jPPeixe;
    private javax.swing.JRadioButton jRBLobo;
    private javax.swing.JRadioButton jRBPeixe;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFDataNascimentoLobo;
    private javax.swing.JTextField jTFDescricaoAnimal;
    private javax.swing.JTextField jTFDescricaoGrupo;
    private javax.swing.JTextField jTFNomeGrupo;
    private javax.swing.JTextField jTFPesoLobo;
    private javax.swing.JTextField jTFStatusAnimal;
    private javax.swing.JTextField jTFTamanhoLobo;
    private javax.swing.JTextField jTFTipoPeixe;
    // End of variables declaration//GEN-END:variables
}
